/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: header.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "header.pb-c.h"
void   com__example__myfirstapp__header__init
                     (Com__Example__Myfirstapp__Header         *message)
{
  static Com__Example__Myfirstapp__Header init_value = COM__EXAMPLE__MYFIRSTAPP__HEADER__INIT;
  *message = init_value;
}
size_t com__example__myfirstapp__header__get_packed_size
                     (const Com__Example__Myfirstapp__Header *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__example__myfirstapp__header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__example__myfirstapp__header__pack
                     (const Com__Example__Myfirstapp__Header *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__example__myfirstapp__header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__example__myfirstapp__header__pack_to_buffer
                     (const Com__Example__Myfirstapp__Header *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__example__myfirstapp__header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Example__Myfirstapp__Header *
       com__example__myfirstapp__header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Example__Myfirstapp__Header *)
     protobuf_c_message_unpack (&com__example__myfirstapp__header__descriptor,
                                allocator, len, data);
}
void   com__example__myfirstapp__header__free_unpacked
                     (Com__Example__Myfirstapp__Header *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__example__myfirstapp__header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue com__example__myfirstapp__header__method_type__enum_values_by_number[5] =
{
  { "LIST", "COM__EXAMPLE__MYFIRSTAPP__HEADER__METHOD_TYPE__LIST", 0 },
  { "DIFF", "COM__EXAMPLE__MYFIRSTAPP__HEADER__METHOD_TYPE__DIFF", 1 },
  { "PULL", "COM__EXAMPLE__MYFIRSTAPP__HEADER__METHOD_TYPE__PULL", 2 },
  { "LEAVE", "COM__EXAMPLE__MYFIRSTAPP__HEADER__METHOD_TYPE__LEAVE", 3 },
  { "CAP", "COM__EXAMPLE__MYFIRSTAPP__HEADER__METHOD_TYPE__CAP", 4 },
};
static const ProtobufCIntRange com__example__myfirstapp__header__method_type__value_ranges[] = {
{0, 0},{0, 5}
};
const ProtobufCEnumValueIndex com__example__myfirstapp__header__method_type__enum_values_by_name[5] =
{
  { "CAP", 4 },
  { "DIFF", 1 },
  { "LEAVE", 3 },
  { "LIST", 0 },
  { "PULL", 2 },
};
const ProtobufCEnumDescriptor com__example__myfirstapp__header__method_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "com.example.myfirstapp.Header.MethodType",
  "MethodType",
  "Com__Example__Myfirstapp__Header__MethodType",
  "com.example.myfirstapp",
  5,
  com__example__myfirstapp__header__method_type__enum_values_by_number,
  5,
  com__example__myfirstapp__header__method_type__enum_values_by_name,
  1,
  com__example__myfirstapp__header__method_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor com__example__myfirstapp__header__field_descriptors[3] =
{
  {
    "method",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Example__Myfirstapp__Header, method),
    &com__example__myfirstapp__header__method_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Example__Myfirstapp__Header, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indexes",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Example__Myfirstapp__Header, indexes),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__example__myfirstapp__header__field_indices_by_name[] = {
  2,   /* field[2] = indexes */
  1,   /* field[1] = length */
  0,   /* field[0] = method */
};
static const ProtobufCIntRange com__example__myfirstapp__header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__example__myfirstapp__header__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "com.example.myfirstapp.Header",
  "Header",
  "Com__Example__Myfirstapp__Header",
  "com.example.myfirstapp",
  sizeof(Com__Example__Myfirstapp__Header),
  3,
  com__example__myfirstapp__header__field_descriptors,
  com__example__myfirstapp__header__field_indices_by_name,
  1,  com__example__myfirstapp__header__number_ranges,
  (ProtobufCMessageInit) com__example__myfirstapp__header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
