/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: song.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "song.pb-c.h"
void   com__example__myfirstapp__song__init
                     (Com__Example__Myfirstapp__Song         *message)
{
  static Com__Example__Myfirstapp__Song init_value = COM__EXAMPLE__MYFIRSTAPP__SONG__INIT;
  *message = init_value;
}
size_t com__example__myfirstapp__song__get_packed_size
                     (const Com__Example__Myfirstapp__Song *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__example__myfirstapp__song__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__example__myfirstapp__song__pack
                     (const Com__Example__Myfirstapp__Song *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__example__myfirstapp__song__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__example__myfirstapp__song__pack_to_buffer
                     (const Com__Example__Myfirstapp__Song *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__example__myfirstapp__song__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Example__Myfirstapp__Song *
       com__example__myfirstapp__song__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Example__Myfirstapp__Song *)
     protobuf_c_message_unpack (&com__example__myfirstapp__song__descriptor,
                                allocator, len, data);
}
void   com__example__myfirstapp__song__free_unpacked
                     (Com__Example__Myfirstapp__Song *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &com__example__myfirstapp__song__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__example__myfirstapp__song__field_descriptors[3] =
{
  {
    "title",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Example__Myfirstapp__Song, title),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checksum",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Example__Myfirstapp__Song, checksum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lenOfSong",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Com__Example__Myfirstapp__Song, lenofsong),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__example__myfirstapp__song__field_indices_by_name[] = {
  1,   /* field[1] = checksum */
  2,   /* field[2] = lenOfSong */
  0,   /* field[0] = title */
};
static const ProtobufCIntRange com__example__myfirstapp__song__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor com__example__myfirstapp__song__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "com.example.myfirstapp.Song",
  "Song",
  "Com__Example__Myfirstapp__Song",
  "com.example.myfirstapp",
  sizeof(Com__Example__Myfirstapp__Song),
  3,
  com__example__myfirstapp__song__field_descriptors,
  com__example__myfirstapp__song__field_indices_by_name,
  1,  com__example__myfirstapp__song__number_ranges,
  (ProtobufCMessageInit) com__example__myfirstapp__song__init,
  NULL,NULL,NULL    /* reserved[123] */
};
