// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: C:\Users\asaltiel\Documents\GT\Fall 2013\CS 3251 - A\Projects\Project_4\Server\structs.proto
package com.example.myfirstapp;

import com.squareup.wire.ByteString;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.BYTES;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class Song extends Message {

  public static final String DEFAULT_TITLE = "";
  public static final ByteString DEFAULT_CHECKSUM = ByteString.EMPTY;
  public static final Integer DEFAULT_LENOFSONG = 0;
  public static final Boolean DEFAULT_CAPLIMITSKIP = false;

  @ProtoField(tag = 1, type = STRING, label = REQUIRED)
  public final String title;

  @ProtoField(tag = 2, type = BYTES, label = REQUIRED)
  public final ByteString checksum;

  @ProtoField(tag = 3, type = INT32, label = REQUIRED)
  public final Integer lenofsong;

  @ProtoField(tag = 4, type = BOOL)
  public final Boolean caplimitskip;

  private Song(Builder builder) {
    super(builder);
    this.title = builder.title;
    this.checksum = builder.checksum;
    this.lenofsong = builder.lenofsong;
    this.caplimitskip = builder.caplimitskip;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Song)) return false;
    Song o = (Song) other;
    return equals(title, o.title)
        && equals(checksum, o.checksum)
        && equals(lenofsong, o.lenofsong)
        && equals(caplimitskip, o.caplimitskip);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = title != null ? title.hashCode() : 0;
      result = result * 37 + (checksum != null ? checksum.hashCode() : 0);
      result = result * 37 + (lenofsong != null ? lenofsong.hashCode() : 0);
      result = result * 37 + (caplimitskip != null ? caplimitskip.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Song> {

    public String title;
    public ByteString checksum;
    public Integer lenofsong;
    public Boolean caplimitskip;

    public Builder() {
    }

    public Builder(Song message) {
      super(message);
      if (message == null) return;
      this.title = message.title;
      this.checksum = message.checksum;
      this.lenofsong = message.lenofsong;
      this.caplimitskip = message.caplimitskip;
    }

    public Builder title(String title) {
      this.title = title;
      return this;
    }

    public Builder checksum(ByteString checksum) {
      this.checksum = checksum;
      return this;
    }

    public Builder lenofsong(Integer lenofsong) {
      this.lenofsong = lenofsong;
      return this;
    }

    public Builder caplimitskip(Boolean caplimitskip) {
      this.caplimitskip = caplimitskip;
      return this;
    }

    @Override
    public Song build() {
      checkRequiredFields();
      return new Song(this);
    }
  }
}
