/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: song.proto */

#ifndef PROTOBUF_C_song_2eproto__INCLUDED
#define PROTOBUF_C_song_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Song Song;


/* --- enums --- */


/* --- messages --- */

struct  _Song
{
  ProtobufCMessage base;
  char *title;
  char *checksum;
  int32_t lenofsong;
};
#define SONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&song__descriptor) \
    , NULL, NULL, 0 }


/* Song methods */
void   song__init
                     (Song         *message);
size_t song__get_packed_size
                     (const Song   *message);
size_t song__pack
                     (const Song   *message,
                      uint8_t             *out);
size_t song__pack_to_buffer
                     (const Song   *message,
                      ProtobufCBuffer     *buffer);
Song *
       song__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   song__free_unpacked
                     (Song *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Song_Closure)
                 (const Song *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor song__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_song_2eproto__INCLUDED */
