/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: song.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "song.pb-c.h"
void   song__init
                     (Song         *message)
{
  static Song init_value = SONG__INIT;
  *message = init_value;
}
size_t song__get_packed_size
                     (const Song *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &song__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t song__pack
                     (const Song *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &song__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t song__pack_to_buffer
                     (const Song *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &song__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Song *
       song__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Song *)
     protobuf_c_message_unpack (&song__descriptor,
                                allocator, len, data);
}
void   song__free_unpacked
                     (Song *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &song__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor song__field_descriptors[3] =
{
  {
    "title",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Song, title),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checksum",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Song, checksum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lenOfSong",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Song, lenofsong),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned song__field_indices_by_name[] = {
  1,   /* field[1] = checksum */
  2,   /* field[2] = lenOfSong */
  0,   /* field[0] = title */
};
static const ProtobufCIntRange song__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor song__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Song",
  "Song",
  "Song",
  "",
  sizeof(Song),
  3,
  song__field_descriptors,
  song__field_indices_by_name,
  1,  song__number_ranges,
  (ProtobufCMessageInit) song__init,
  NULL,NULL,NULL    /* reserved[123] */
};
