/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: song.proto */

#ifndef PROTOBUF_C_song_2eproto__INCLUDED
#define PROTOBUF_C_song_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Com__Example__Myfirstapp__Song Com__Example__Myfirstapp__Song;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Example__Myfirstapp__Song
{
  ProtobufCMessage base;
  char *title;
  char *checksum;
  int32_t lenofsong;
};
#define COM__EXAMPLE__MYFIRSTAPP__SONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__example__myfirstapp__song__descriptor) \
    , NULL, NULL, 0 }


/* Com__Example__Myfirstapp__Song methods */
void   com__example__myfirstapp__song__init
                     (Com__Example__Myfirstapp__Song         *message);
size_t com__example__myfirstapp__song__get_packed_size
                     (const Com__Example__Myfirstapp__Song   *message);
size_t com__example__myfirstapp__song__pack
                     (const Com__Example__Myfirstapp__Song   *message,
                      uint8_t             *out);
size_t com__example__myfirstapp__song__pack_to_buffer
                     (const Com__Example__Myfirstapp__Song   *message,
                      ProtobufCBuffer     *buffer);
Com__Example__Myfirstapp__Song *
       com__example__myfirstapp__song__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__example__myfirstapp__song__free_unpacked
                     (Com__Example__Myfirstapp__Song *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Example__Myfirstapp__Song_Closure)
                 (const Com__Example__Myfirstapp__Song *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__example__myfirstapp__song__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_song_2eproto__INCLUDED */
