/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: structs.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "structs.pb-c.h"
void   header__init
                     (Header         *message)
{
  static Header init_value = HEADER__INIT;
  *message = init_value;
}
size_t header__get_packed_size
                     (const Header *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t header__pack
                     (const Header *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t header__pack_to_buffer
                     (const Header *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Header *
       header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Header *)
     protobuf_c_message_unpack (&header__descriptor,
                                allocator, len, data);
}
void   header__free_unpacked
                     (Header *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   song__init
                     (Song         *message)
{
  static Song init_value = SONG__INIT;
  *message = init_value;
}
size_t song__get_packed_size
                     (const Song *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &song__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t song__pack
                     (const Song *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &song__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t song__pack_to_buffer
                     (const Song *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &song__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Song *
       song__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Song *)
     protobuf_c_message_unpack (&song__descriptor,
                                allocator, len, data);
}
void   song__free_unpacked
                     (Song *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &song__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue header__method_type__enum_values_by_number[5] =
{
  { "LIST", "HEADER__METHOD_TYPE__LIST", 0 },
  { "DIFF", "HEADER__METHOD_TYPE__DIFF", 1 },
  { "PULL", "HEADER__METHOD_TYPE__PULL", 2 },
  { "LEAVE", "HEADER__METHOD_TYPE__LEAVE", 3 },
  { "CAP", "HEADER__METHOD_TYPE__CAP", 4 },
};
static const ProtobufCIntRange header__method_type__value_ranges[] = {
{0, 0},{0, 5}
};
const ProtobufCEnumValueIndex header__method_type__enum_values_by_name[5] =
{
  { "CAP", 4 },
  { "DIFF", 1 },
  { "LEAVE", 3 },
  { "LIST", 0 },
  { "PULL", 2 },
};
const ProtobufCEnumDescriptor header__method_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Header.MethodType",
  "MethodType",
  "Header__MethodType",
  "",
  5,
  header__method_type__enum_values_by_number,
  5,
  header__method_type__enum_values_by_name,
  1,
  header__method_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor header__field_descriptors[3] =
{
  {
    "method",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Header, method),
    &header__method_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "limit",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Header, has_limit),
    PROTOBUF_C_OFFSETOF(Header, limit),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "songs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Header, n_songs),
    PROTOBUF_C_OFFSETOF(Header, songs),
    &song__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned header__field_indices_by_name[] = {
  1,   /* field[1] = limit */
  0,   /* field[0] = method */
  2,   /* field[2] = songs */
};
static const ProtobufCIntRange header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor header__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Header",
  "Header",
  "Header",
  "",
  sizeof(Header),
  3,
  header__field_descriptors,
  header__field_indices_by_name,
  1,  header__number_ranges,
  (ProtobufCMessageInit) header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor song__field_descriptors[4] =
{
  {
    "title",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Song, title),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checksum",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Song, checksum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lenofsong",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Song, lenofsong),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "caplimitskip",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Song, has_caplimitskip),
    PROTOBUF_C_OFFSETOF(Song, caplimitskip),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned song__field_indices_by_name[] = {
  3,   /* field[3] = caplimitskip */
  1,   /* field[1] = checksum */
  2,   /* field[2] = lenofsong */
  0,   /* field[0] = title */
};
static const ProtobufCIntRange song__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor song__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Song",
  "Song",
  "Song",
  "",
  sizeof(Song),
  4,
  song__field_descriptors,
  song__field_indices_by_name,
  1,  song__number_ranges,
  (ProtobufCMessageInit) song__init,
  NULL,NULL,NULL    /* reserved[123] */
};
